version: "3.8"

services:
  db:
    image: postgres:13-alpine
    container_name: lab-inventory-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "797315qQ!"
      POSTGRES_DB: lab-inventory
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lab-inventory-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:797315qQ!@db:5432/lab-inventory"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lab-inventory-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  